using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GameGalaxy.Models
{
    internal class ConfigureGamePlatforms : IEntityTypeConfiguration<GamePlatform>
    {
        public void Configure(EntityTypeBuilder<GamePlatform> entity)
        {
            // Set Price column to money data type
            entity.Property(gp => gp.Price).HasColumnType("money");

            // Configure the Composite key for the GamePlatform entity
            entity.HasKey(gp => new { gp.GameId, gp.PlatformId });

            // Configure the relationship between the GamePlatform and Games entities
            entity.HasOne(gp => gp.Game).WithMany(g => g.GamePlatforms).HasForeignKey(gp => gp.GameId);

            // Configure the relationship between the GamePlatform and Platform entities
            entity.HasOne(gp => gp.Platform).WithMany(p => p.GamePlatforms).HasForeignKey(gp => gp.PlatformId);

            entity.HasData(
                new GamePlatform { GameId = 1, PlatformId = 1, Price = 41.90 },
                new GamePlatform { GameId = 1, PlatformId = 2, Price = 30.00 },
                new GamePlatform { GameId = 1, PlatformId = 3, Price = 30.00 },
                new GamePlatform { GameId = 2, PlatformId = 1, Price = 67.90 },
                new GamePlatform { GameId = 2, PlatformId = 2, Price = 60.90 },
                new GamePlatform { GameId = 3, PlatformId = 4, Price = 79.90 },
                new GamePlatform { GameId = 4, PlatformId = 1, Price = 49.90 },
                new GamePlatform { GameId = 4, PlatformId = 2, Price = 79.90 },
                new GamePlatform { GameId = 4, PlatformId = 3, Price = 64.90 },
                new GamePlatform { GameId = 5, PlatformId = 1, Price = 79.90 },
                new GamePlatform { GameId = 5, PlatformId = 2, Price = 69.90 },
                new GamePlatform { GameId = 5, PlatformId = 3, Price = 69.90 },
                new GamePlatform { GameId = 6, PlatformId = 1, Price = 67.90 },
                new GamePlatform { GameId = 6, PlatformId = 2, Price = 64.90 },
                new GamePlatform { GameId = 7, PlatformId = 1, Price = 79.90 },
                new GamePlatform { GameId = 7, PlatformId = 2, Price = 67.90 },
                new GamePlatform { GameId = 8, PlatformId = 1, Price = 79.90 },
                new GamePlatform { GameId = 8, PlatformId = 3, Price = 74.90 },
                new GamePlatform { GameId = 9, PlatformId = 1, Price = 79.90 },
                new GamePlatform { GameId = 9, PlatformId = 2, Price = 79.90 },
                new GamePlatform { GameId = 9, PlatformId = 3, Price = 79.90 },
                new GamePlatform { GameId = 10, PlatformId = 4, Price = 79.90 },
                new GamePlatform { GameId = 11, PlatformId = 4, Price = 79.90 },
                new GamePlatform { GameId = 12, PlatformId = 1, Price = 84.00 },
                new GamePlatform { GameId = 12, PlatformId = 2, Price = 70.70 },
                new GamePlatform { GameId = 12, PlatformId = 3, Price = 64.90 },
                new GamePlatform { GameId = 13, PlatformId = 1, Price = 25.00 },
                new GamePlatform { GameId = 13, PlatformId = 2, Price = 35.54 },
                new GamePlatform { GameId = 13, PlatformId = 3, Price = 36.00 },
                new GamePlatform { GameId = 13, PlatformId = 4, Price = 36.95 },
                new GamePlatform { GameId = 14, PlatformId = 1, Price = 84.00 },
                new GamePlatform { GameId = 14, PlatformId = 2, Price = 86.08 },
                new GamePlatform { GameId = 14, PlatformId = 3, Price = 79.40 },
                new GamePlatform { GameId = 15, PlatformId = 1, Price = 67.89 },
                new GamePlatform { GameId = 15, PlatformId = 2, Price = 69.00 },
                new GamePlatform { GameId = 16, PlatformId = 4, Price = 79.90 },
                new GamePlatform { GameId = 17, PlatformId = 4, Price = 79.90 },
                new GamePlatform { GameId = 18, PlatformId = 4, Price = 79.90 },
                new GamePlatform { GameId = 19, PlatformId = 1, Price = 79.90 },
                new GamePlatform { GameId = 19, PlatformId = 2, Price = 97.90 },
                new GamePlatform { GameId = 20, PlatformId = 1, Price = 81.90 },
                new GamePlatform { GameId = 20, PlatformId = 3, Price = 81.75 },
                new GamePlatform { GameId = 21, PlatformId = 1, Price = 79.90 },
                new GamePlatform { GameId = 21, PlatformId = 2, Price = 86.49 },
                new GamePlatform { GameId = 21, PlatformId = 3, Price = 78.75 },
                new GamePlatform { GameId = 22, PlatformId = 1, Price = 67.90 },
                new GamePlatform { GameId = 22, PlatformId = 2, Price = 67.90 },
                new GamePlatform { GameId = 23, PlatformId = 2, Price = 97.90 },
                new GamePlatform { GameId = 24, PlatformId = 1, Price = 84.00 },
                new GamePlatform { GameId = 24, PlatformId = 2, Price = 95.66 },
                new GamePlatform { GameId = 24, PlatformId = 3, Price = 93.90 },
                new GamePlatform { GameId = 25, PlatformId = 1, Price = 103.99 },
                new GamePlatform { GameId = 25, PlatformId = 2, Price = 99.74 },
                new GamePlatform { GameId = 25, PlatformId = 3, Price = 119.99 },
                new GamePlatform { GameId = 26, PlatformId = 1, Price = 49.90 },
                new GamePlatform { GameId = 26, PlatformId = 2, Price = 55.93 },
                new GamePlatform { GameId = 26, PlatformId = 3, Price = 54.90 },
                new GamePlatform { GameId = 26, PlatformId = 4, Price = 59.95 },
                new GamePlatform { GameId = 27, PlatformId = 1, Price = 79.90 },
                new GamePlatform { GameId = 27, PlatformId = 2, Price = 97.90 },
                new GamePlatform { GameId = 28, PlatformId = 1, Price = 54.00 },
                new GamePlatform { GameId = 28, PlatformId = 2, Price = 55.01 },
                new GamePlatform { GameId = 28, PlatformId = 3, Price = 54.00 },
                new GamePlatform { GameId = 29, PlatformId = 1, Price = 79.90 },
                new GamePlatform { GameId = 29, PlatformId = 2, Price = 97.90 },
                new GamePlatform { GameId = 30, PlatformId = 1, Price = 87.00 },
                new GamePlatform { GameId = 30, PlatformId = 2, Price = 86.49 },
                new GamePlatform { GameId = 30, PlatformId = 3, Price = 84.75 },
                new GamePlatform { GameId = 31, PlatformId = 1, Price = 79.90 },
                new GamePlatform { GameId = 31, PlatformId = 2, Price = 86.38 },
                new GamePlatform { GameId = 31, PlatformId = 3, Price = 84.75 },
                new GamePlatform { GameId = 32, PlatformId = 1, Price = 18.50 },
                new GamePlatform { GameId = 32, PlatformId = 2, Price = 28.42 },
                new GamePlatform { GameId = 32, PlatformId = 3, Price = 29.25 },
                new GamePlatform { GameId = 32, PlatformId = 4, Price = 28.95 },
                new GamePlatform { GameId = 33, PlatformId = 1, Price = 79.90 },
                new GamePlatform { GameId = 33, PlatformId = 3, Price = 79.90 },
                new GamePlatform { GameId = 34, PlatformId = 4, Price = 79.90 },
                new GamePlatform { GameId = 35, PlatformId = 4, Price = 79.90 },
                new GamePlatform { GameId = 36, PlatformId = 1, Price = 81.90 },
                new GamePlatform { GameId = 36, PlatformId = 3, Price = 81.90 },
                new GamePlatform { GameId = 37, PlatformId = 4, Price = 79.90 },
                new GamePlatform { GameId = 38, PlatformId = 1, Price = 35.99 },
                new GamePlatform { GameId = 38, PlatformId = 2, Price = 55.93 },
                new GamePlatform { GameId = 38, PlatformId = 3, Price = 57.75 },
                new GamePlatform { GameId = 38, PlatformId = 4, Price = 60.00 },
                new GamePlatform { GameId = 39, PlatformId = 1, Price = 79.90 },
                new GamePlatform { GameId = 39, PlatformId = 2, Price = 79.90 },
                new GamePlatform { GameId = 40, PlatformId = 1, Price = 119.90 },
                new GamePlatform { GameId = 40, PlatformId = 2, Price = 119.90 },
                new GamePlatform { GameId = 40, PlatformId = 3, Price = 119.90 },
                new GamePlatform { GameId = 41, PlatformId = 2, Price = 97.90 },
                new GamePlatform { GameId = 42, PlatformId = 1, Price = 81.30 },
                new GamePlatform { GameId = 42, PlatformId = 2, Price = 82.82 },
                new GamePlatform { GameId = 42, PlatformId = 3, Price = 80.25 },
                new GamePlatform { GameId = 43, PlatformId = 1, Price = 29.00 },
                new GamePlatform { GameId = 43, PlatformId = 2, Price = 42.68 },
                new GamePlatform { GameId = 43, PlatformId = 3, Price = 43.50 },
                new GamePlatform { GameId = 44, PlatformId = 1, Price = 79.90 },
                new GamePlatform { GameId = 44, PlatformId = 2, Price = 97.90 },
                new GamePlatform { GameId = 45, PlatformId = 1, Price = 98.00 },
                new GamePlatform { GameId = 45, PlatformId = 2, Price = 95.66 },
                new GamePlatform { GameId = 45, PlatformId = 3, Price = 93.90 },
                new GamePlatform { GameId = 46, PlatformId = 1, Price = 79.90 },
                new GamePlatform { GameId = 46, PlatformId = 2, Price = 97.90 },
                new GamePlatform { GameId = 47, PlatformId = 4, Price = 79.90 },
                new GamePlatform { GameId = 48, PlatformId = 4, Price = 79.90 },
                new GamePlatform { GameId = 49, PlatformId = 1, Price = 97.90 },
                new GamePlatform { GameId = 49, PlatformId = 2, Price = 97.90 },
                new GamePlatform { GameId = 50, PlatformId = 1, Price = 79.90 },
                new GamePlatform { GameId = 50, PlatformId = 2, Price = 101.84 },
                new GamePlatform { GameId = 50, PlatformId = 3, Price = 99.00 },
                new GamePlatform { GameId = 50, PlatformId = 4, Price = 89.95 },
                new GamePlatform { GameId = 51, PlatformId = 1, Price = 54.10 },
                new GamePlatform { GameId = 51, PlatformId = 2, Price = 54.60 },
                new GamePlatform { GameId = 51, PlatformId = 3, Price = 54.10 },
                new GamePlatform { GameId = 52, PlatformId = 4, Price = 87.90 },
                new GamePlatform { GameId = 53, PlatformId = 1, Price = 98.00 },
                new GamePlatform { GameId = 53, PlatformId = 2, Price = 98.00 },
                new GamePlatform { GameId = 53, PlatformId = 3, Price = 98.00 },
                new GamePlatform { GameId = 54, PlatformId = 1, Price = 69.00 },
                new GamePlatform { GameId = 54, PlatformId = 2, Price = 81.39 },
                new GamePlatform { GameId = 54, PlatformId = 3, Price = 74.25 },
                new GamePlatform { GameId = 55, PlatformId = 1, Price = 84.90 },
                new GamePlatform { GameId = 55, PlatformId = 2, Price = 95.78 },
                new GamePlatform { GameId = 55, PlatformId = 3, Price = 94.90 },
                new GamePlatform { GameId = 55, PlatformId = 4, Price = 89.95 },
                new GamePlatform { GameId = 56, PlatformId = 1, Price = 64.90 },
                new GamePlatform { GameId = 56, PlatformId = 2, Price = 70.54 },
                new GamePlatform { GameId = 56, PlatformId = 3, Price = 69.75 },
                new GamePlatform { GameId = 57, PlatformId = 2, Price = 97.90 },
                new GamePlatform { GameId = 58, PlatformId = 1, Price = 69.80 },
                new GamePlatform { GameId = 58, PlatformId = 2, Price = 85.38 },
                new GamePlatform { GameId = 58, PlatformId = 3, Price = 83.76 },
                new GamePlatform { GameId = 59, PlatformId = 1, Price = 94.00 },
                new GamePlatform { GameId = 59, PlatformId = 2, Price = 94.87 },
                new GamePlatform { GameId = 59, PlatformId = 3, Price = 94.00 },
                new GamePlatform { GameId = 60, PlatformId = 1, Price = 94.90 },
                new GamePlatform { GameId = 60, PlatformId = 2, Price = 98.81 },
                new GamePlatform { GameId = 60, PlatformId = 3, Price = 98.25 },
                new GamePlatform { GameId = 61, PlatformId = 1, Price = 54.90 },
                new GamePlatform { GameId = 61, PlatformId = 2, Price = 54.90 },
                new GamePlatform { GameId = 61, PlatformId = 3, Price = 54.75 },
                new GamePlatform { GameId = 61, PlatformId = 4, Price = 59.95 },
                new GamePlatform { GameId = 62, PlatformId = 1, Price = 26.00 },
                new GamePlatform { GameId = 62, PlatformId = 3, Price = 43.50 },
                new GamePlatform { GameId = 63, PlatformId = 2, Price = 67.90 },
                new GamePlatform { GameId = 64, PlatformId = 1, Price = 97.90 },
                new GamePlatform { GameId = 64, PlatformId = 2, Price = 97.89 },
                new GamePlatform { GameId = 64, PlatformId = 3, Price = 97.90 },
                new GamePlatform { GameId = 65, PlatformId = 2, Price = 97.90 },
                new GamePlatform { GameId = 66, PlatformId = 2, Price = 97.90 },
                new GamePlatform { GameId = 67, PlatformId = 1, Price = 79.90 },
                new GamePlatform { GameId = 67, PlatformId = 2, Price = 81.39 },
                new GamePlatform { GameId = 68, PlatformId = 1, Price = 98.00 },
                new GamePlatform { GameId = 68, PlatformId = 2, Price = 98.00 },
                new GamePlatform { GameId = 68, PlatformId = 3, Price = 98.00 },
                new GamePlatform { GameId = 69, PlatformId = 1, Price = 94.90 },
                new GamePlatform { GameId = 69, PlatformId = 2, Price = 97.90 },
                new GamePlatform { GameId = 69, PlatformId = 3, Price = 98.25 },
                new GamePlatform { GameId = 70, PlatformId = 2, Price = 97.90 },
                new GamePlatform { GameId = 70, PlatformId = 3, Price = 97.90 }
                );
        }
    }
}
